### Generate Passpot JWT Token
POST http://localhost:8080/token
Content-Type: application/json

{
  "userUuid": "85b73dbd-44da-4d22-8e62-518f67faac38",
  "email": "kimzerovirus@email.com",
  "lastName": "kim",
  "firstName": "zerovirus"
}

### Parse Passport JWT Token
GET http://localhost:8080/passport
X-PASSPORT-TOKEN: eyJhbGciOiJIUzUxMiJ9.eyJwYXNzcG9ydCI6eyJ1c2VyVXVpZCI6Ijg1YjczZGJkLTQ0ZGEtNGQyMi04ZTYyLTUxOGY2N2ZhYWMzOCIsImVtYWlsIjoia2ltemVyb3ZpcnVzQGVtYWlsLmNvbSIsImZpcnN0TmFtZSI6Inplcm92aXJ1cyIsImxhc3ROYW1lIjoia2ltIn0sImV4cCI6MTcxMjQwMTE4NH0.Eibeat1B-f0dua3FHUF9NTz4E35Hq_1Euvsew4PE6mvpNJDESIkfI2XGx6JkVdOUJE9SZCNvzjp9CfTYrdNB8g